### ISSUE TITLE
Use better Icon for hyphens Button

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.Neos.Hyphens#1]
The dash might not be the best choice.

**Comment by ulbrich-media** [comment]
According to the [soft hyphen wikipedia article](https://en.wikipedia.org/wiki/Soft_hyphen) there is an official ISO icon for it. Practically a dash inside of brackets. 

Not quite sure if this is more understandable for an editor, but probably better then a dash only.

**Comment by Sebobo** [comment]
Good idea, thanks.
