### ISSUE TITLE
Dimensions of the characters and the shy delimiter are not correct when using big Font Sizes

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Neos.Hyphens#10]
# Problem
When using Shel.Neos.Hyphens with "big" (69px) Font-Sizes the dimensions of the characters and the shy delimiter are not correct. 

![image](https://user-images.githubusercontent.com/1118783/60277073-2536b180-98fd-11e9-8541-9c0517a8c0d5.png)
_left: Standard Delimiter_
_right: Shy Delimiter_

# Possible Solution
Using `content: '-';` without any more styles (like position absolute)  fixes the problem in my Case. 
![image](https://user-images.githubusercontent.com/1118783/60277463-df2e1d80-98fd-11e9-9d05-db9455b5591f.png)

Im not sure if there is reason you are using `position:absolute; ` etc.

**Comment by Sebobo** [comment]
Thanks for the issue!

It took me while to get the element to position right and to not break the spell correction. That's why I set content empty and used the border to render a line.

**Comment by Sebobo** [comment]
I tested a bit and I think setting `border-bottom: .1em solid currentColor` should solve it too. Then it would be relative to the fontsize.

**Comment by paavo** [comment]
@Sebobo works well, thanks! but the width should be relative too, 
i tested around with `width: .2em;` what looks like a good ratio to me..
