### ISSUE TITLE
&nbsp; does break in editing mode

### ISSUE THREAD

**Issue by jobee** [Sebobo/Shel.Neos.Hyphens#48]
Due to the extra `<span />` markup (which I guess is needed for ckeditor to work?), inserted non-breaking spaces do break in backend editing mode. The editor experience could largely benefit from simulating the actual result.

![Screenshot 2021-09-17 at 09 27 11](https://user-images.githubusercontent.com/5636715/133742728-07e5d5e9-6c92-4996-9da1-d3b0534c2ed3.png)
```html
<span>Confidence in uncertain<span class="nbsp">&nbsp;</span>times</span>
```

**Comment by jobee** [comment]
Ok, it seems the extra `span` is just there for styling reasons. I'm really not sure which is more useful in editing. Making non-breaking spacing visible or showing the actual result. It depends on the needs of the project, I guess.

Adding another `span` which includes the surrounding words could work. But this probably comes with side effects, if there are other tags applied already...

```html
<span>Confidence in <span class="nbsp-simulate">uncertain<span class="nbsp">&nbsp;</span>times</span></span>

.nbsp-simulate {
  display: inline-block;
}
```

**Comment by Sebobo** [comment]
The span is needed to make the symbol selectable and visible.

Automatically wrapping the word or sentence is probably not eassily possible imo, due to the way CK works. And as you say might have other side effects. 

Maybe there is another CSS trick we could use.

**Comment by jobee** [comment]
Hm, I don't think this is possible without additional markup :-(
But how about changing the nbsp editing at all?

1. Select words that should wrap in a new line together
2. Wrap them with `<span style="white-space:nowrap;">Long line with no breaks</span>`

**Update**
~~Thinking about it, this is possible with https://github.com/techdivision/ckstyles too.
No need to propose a breaking change for this package, unless you're unhappy with the current behaviour as well~~

After testing: The mentioned package introduced even more unnecessary markup while editing back and forth. I'll stick to your package and train the imagination of the editors :-P
