### ISSUE TITLE
Not compatible with Neos CMS 3.3 (not ootb)

### ISSUE THREAD

**Issue by KPeschke** [Sebobo/Shel.Neos.Hyphens#9]
"Neos.Fusion:Join"  exists since Neos 4.2, before "Neos.Fusion:Array".

Tested with Neos v3.3.21 and UI 2.4

Don't know if a version query exists in Fusion to use a case.

After adding an override ... works like a charm :)

**Comment by Sebobo** [comment]
Thanks! Fixed in 1.0.1 :)
